In [1]:
import numpy as np


In [2]:
x1 = np.array([2,6,5,1])
print(x1)


[2 6 5 1]


In [3]:
print(type(x1))


<class 'numpy.ndarray'>


-create
-properties
-operations and methods

In [4]:
x1 = np.array([1,3,4])
print(x1)
print(x1.shape)
print(x1.size)
print(x1.ndim)

[1 3 4]
(3,)
3
1


In [6]:
x2 = np.array([
    [1,2,3,5],
    [4,5,6,2]
])
print(x2)
print(x2.shape)
print(x2.size)
print(x2.ndim)


[[1 2 3 5]
 [4 5 6 2]]
(2, 4)
8
2


In [9]:
a = np.arange(1,11,.25)
print(a)
print('shape =>', a.shape, 'size=>',a.size, 'dimension=>',a.ndim)


[ 1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75
  4.    4.25  4.5   4.75  5.    5.25  5.5   5.75  6.    6.25  6.5   6.75
  7.    7.25  7.5   7.75  8.    8.25  8.5   8.75  9.    9.25  9.5   9.75
 10.   10.25 10.5  10.75]
shape => (40,) size=> 40 dimension=> 1


In [10]:
b = np.linspace(1,11,20)
print(b)
print('shape =>', b.shape, 'size=>',b.size, 'dimension=>',b.ndim)


[ 1.          1.52631579  2.05263158  2.57894737  3.10526316  3.63157895
  4.15789474  4.68421053  5.21052632  5.73684211  6.26315789  6.78947368
  7.31578947  7.84210526  8.36842105  8.89473684  9.42105263  9.94736842
 10.47368421 11.        ]
shape => (20,) size=> 20 dimension=> 1


In [11]:
c = np.random.randint(-5, 6, (5,5)) # 5*5 matrix in range of -5 to 5
print(c)

[[-1 -2  1 -5  4]
 [ 5  3  0 -1 -4]
 [-4  4  0  1  0]
 [ 1 -1  3 -2  0]
 [-1  1 -4 -4 -4]]


In [12]:
# check datatype of array elements
print(c.dtype)

int32


In [14]:
b.reshape(5,4)

array([[ 1.        ,  1.52631579,  2.05263158,  2.57894737],
       [ 3.10526316,  3.63157895,  4.15789474,  4.68421053],
       [ 5.21052632,  5.73684211,  6.26315789,  6.78947368],
       [ 7.31578947,  7.84210526,  8.36842105,  8.89473684],
       [ 9.42105263,  9.94736842, 10.47368421, 11.        ]])

In [15]:
b.reshape(2,5,2)

array([[[ 1.        ,  1.52631579],
        [ 2.05263158,  2.57894737],
        [ 3.10526316,  3.63157895],
        [ 4.15789474,  4.68421053],
        [ 5.21052632,  5.73684211]],

       [[ 6.26315789,  6.78947368],
        [ 7.31578947,  7.84210526],
        [ 8.36842105,  8.89473684],
        [ 9.42105263,  9.94736842],
        [10.47368421, 11.        ]]])

In [16]:
# converting n-dim array to 1-dim array
c.flatten()

array([-1, -2,  1, -5,  4,  5,  3,  0, -1, -4, -4,  4,  0,  1,  0,  1, -1,
        3, -2,  0, -1,  1, -4, -4, -4])

In [17]:
# operations
a = np.array([1,2,3,4,5,6]).reshape(2,3)
b = np.array([5,2,1,2,2,6]).reshape(2,3)
print(a)
print(b)
print('element-wise addition')
ans = a + b
print(ans)
print('element-wise subtraction')
ans = a - b
print(ans)
print('element-wise multiplication')
ans = a * b
print(ans)


[[1 2 3]
 [4 5 6]]
[[5 2 1]
 [2 2 6]]
element-wise addition
[[ 6  4  4]
 [ 6  7 12]]
element-wise subtraction
[[-4  0  2]
 [ 2  3  0]]
element-wise multiplication
[[ 5  4  3]
 [ 8 10 36]]


In [18]:
# matrix multiplication - dot product
a = np.array([1,2,3,4,5,6]).reshape(2,3)
b = np.array([5,2,1,2,2,6]).reshape(3,2)
print(a)
print(b)
print(a@b) #np.dot(1,b)

[[1 2 3]
 [4 5 6]]
[[5 2]
 [1 2]
 [2 6]]
[[13 24]
 [37 54]]


In [20]:
# transpose of matrix
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [21]:
# statistical operations
print(a.sum()) #all item
print(a.sum(axis=1)) #row-wise sum
print(a.sum(axis=0)) #col-wise sum

#same logic can be applied to functions
print(a.mean())
print(a.mean(axis=1))
print(a.mean(axis=0))

21
[ 6 15]
[5 7 9]
3.5
[2. 5.]
[2.5 3.5 4.5]


In [ ]:
#min, max, arfmin, argmax, std, var, cumsum, 


Slicing

In [22]:
x = np.linspace(10,99,100).reshape(10,10).astype(int)
print(x)

[[10 10 11 12 13 14 15 16 17 18]
 [18 19 20 21 22 23 24 25 26 27]
 [27 28 29 30 31 32 33 34 35 36]
 [36 37 38 39 40 41 42 43 44 45]
 [45 46 47 48 49 50 51 52 53 54]
 [54 55 56 57 58 59 60 61 62 63]
 [63 64 65 66 67 68 69 70 71 72]
 [72 73 74 75 76 77 78 79 80 81]
 [81 82 83 84 85 86 87 88 89 90]
 [90 91 92 93 94 95 96 97 98 99]]


1D slicing

x[start : stop : step]

2D slicing

x[rstart : rstop : rstep ,  cstart : cstop : cstep]

example x[1:5, :6]

In [23]:
print(x[1:5, :6])

[[18 19 20 21 22 23]
 [27 28 29 30 31 32]
 [36 37 38 39 40 41]
 [45 46 47 48 49 50]]


In [25]:
#3 rd row
print(x[2])
#last row
print(x[-1])
#first col
print(x[:,0])
# 2nd col
print(x[:, 1])
#last col
print(x[:, -1])
#last 3 col
print(x[:, -3:])
# first 3 col
print(x[:, :3])

[27 28 29 30 31 32 33 34 35 36]
[90 91 92 93 94 95 96 97 98 99]
[10 18 27 36 45 54 63 72 81 90]
[10 19 28 37 46 55 64 73 82 91]
[18 27 36 45 54 63 72 81 90 99]
[[16 17 18]
 [25 26 27]
 [34 35 36]
 [43 44 45]
 [52 53 54]
 [61 62 63]
 [70 71 72]
 [79 80 81]
 [88 89 90]
 [97 98 99]]
[[10 10 11]
 [18 19 20]
 [27 28 29]
 [36 37 38]
 [45 46 47]
 [54 55 56]
 [63 64 65]
 [72 73 74]
 [81 82 83]
 [90 91 92]]
